gettext: introduce GIT_TEST_GETTEXT_POISON_SCRAMBLED
Sometimes tests run with GIT_TEST_GETTEXT POISON fail because of a
reason other than a translated string that should not have been
translated.  In such a case an error message from a git command in the
test's verbose output is usually, well, less than helpful:

  error: # GETTEXT POISON #

or

  fatal: # GETTEXT POISON #: No such file or directory

It's especially annoying on those rare occasions when a heisenbug
decides it's a good time to suddenly reveal its presence during a
GIT_TEST_GETTEXT POISON test run, and all we get is an error message
like these (yes, I did actually see both of the above error messages
only once).

Make builtin commands' GETTEXT POISON-ed error messages more useful
for debugging failures by introducing a new mode of poisoning: if
GIT_TEST_GETTEXT_POISON_SCRAMBLED is set to a boolean true, then print
the original untranslated message in a scrambled form, interspersing a
'.' after each character, e.g.:

  error:  U.n.a.b.l.e. .t.o. .c.r.e.a.t.e. .'./home/szeder/src/git/t/trash directory.t1404-update-ref-errors/.git/packed-refs...l.o.c.k.'.:. .File exists...

This way the messages will remain gibberish enough for machine
consumption as they were before, but at the same time they will be
relatively easily legible for humans.  Take extra care to preserve
printf() format conversion specifiers unaltered when inserting those
dots.

Note that GIT_TEST_GETTEXT_POISON_SCRAMBLED is only taken into account
if GIT_TEST_GETTEXT_POISON is set to true as well.

The last test 'env--helper reads config thanks to trace2' in
't0017-env-helper.sh' explicitly enables GIT_TEST_GETTEXT_POISON and
then looks for the GETTEXT_POISON_MAGIC string, but in scrambled mode
it wouldn't find it.  Unset GIT_TEST_GETTEXT_POISON_SCRAMBLED
specifically in that one test.

Leave 'git-sh-i18n.sh' unchanged, because translatable messages in
scripts often include shell variables, and they could (though
currently they don't) include printf format specifiers, parameter
expansions, command substitutions and whatnot, too.  Dealing with
those in a shell script would be too much hassle without its worth.

There is an additional benefit: as this change considerably increases
the size of translated messages, it could detect cases when we try to
format a translated string into a too small buffer.  E.g. this change
applied on old versions causes test failures because of the bug that
was fixed in 2cfa83574c (bisect_next_all: convert xsnprintf to
xstrfmt, 2017-02-16).

[TODO: Fallout?
       A 'printf(_("foo: %s"), var);' call includes the contents of
       'var' unscrambled in the output.  Could that hide the
       translation of a string that should not have been translated?
       I'm afraid yes: to check the output of that printf() a sloppy
       test could do:

         git plumbing-cmd >out && grep "var's content" out

       which would fail in a regular GETTEXT_POISON test run, but
       would succeed in a scrambled test run.  Does this matter in
       practice, do we care at all?

       Does gettext_scramble() need a FORMAT_PRESERVING annotation?
       Seems to work fine without it so far...]

Signed-off-by: SZEDER Gábor <szeder.dev@gmail.com>